### ISSUE TITLE
Prismic data in a navbar in 'layouts' folder.

### ISSUE THREAD

**Issue by tomgalpin** [phillysnow/nuxt-static-test#1]
In a Nuxt app, the navbars should go in the layouts folder.  Can you show how to do this, rather than the workaround you set up here.  For a large scale application, this would be a bit of a mess.

**Comment by phillysnow** [comment]
We were using this model to have different CSS for the menu in different pages based off the wrapper. I wanted to do as you suggested. As there is no way to pass props from the page to the layout, I've created a different layout for the homepage and the default pages. Like this we can have the menu component in the layouts.
